def separate_transcripts_with_same_cmp_ref_geneID(gtf_list):
    processed_dict = {}
    key_counter = 1  # Used for generating unique keys for non-transcript/exon lines

    for line in gtf_list:
        fields = line.split('\t')
        if fields[2] in ['transcript', 'exon']:
            start_position = fields[3] if fields[2] == 'transcript' else start_position
            
#             my_dict = {}
# my_dict.setdefault('key1', []).append('value1')
# # 'key1' doesn't exist initially, so it's created with a default empty list, then 'value1' is appended.

# my_dict.setdefault('key1', []).append('value2')
# # 'key1' already exists, so the existing list is retrieved and 'value2' is appended.

            processed_dict.setdefault(start_position, []).append(line)
        else:
            unique_key = f'unique_key_{key_counter}'
            processed_dict[unique_key] = [line]
            key_counter += 1

    return processed_dict


# test input
gtf_list =[
        "C0006904\tStringTie\ttranscript\t12908\t63426\t.\t-\t.\ttranscript_id \"TCONS_00000306\"; gene_id \"XLOC_000224\"; gene_name \"ALKBH3 [nr]\"; oId \"STRG.34136.2\"; cmp_ref \"AMEX60DDU001001030.1\"; class_code \"j\"; tss_id \"TSS260\";",
        "C0006904\tStringTie\texon\t12908\t12947\t.\t-\t.\ttranscript_id \"TCONS_00000306\"; gene_id \"XLOC_000224\"; exon_number \"1\";",
        "C0006904\tStringTie\texon\t29541\t29650\t.\t-\t.\ttranscript_id \"TCONS_00000306\"; gene_id \"XLOC_000224\"; exon_number \"2\";",
        "C0006904\tStringTie\texon\t63368\t63426\t.\t-\t.\ttranscript_id \"TCONS_00000306\"; gene_id \"XLOC_000224\"; exon_number \"3\";",
        "C0006904\tStringTie\ttranscript\t12908\t63426\t.\t-\t.\ttranscript_id \"TCONS_00000305\"; gene_id \"XLOC_000224\"; gene_name \"ALKBH3 [nr]\"; oId \"STRG.34136.1\"; cmp_ref \"AMEX60DDU001001030.1\"; class_code \"j\"; tss_id \"TSS260\";",
        "C0006904\tStringTie\texon\t12908\t12947\t.\t-\t.\ttranscript_id \"TCONS_00000305\"; gene_id \"XLOC_000224\"; exon_number \"1\";",
        "C0006904\tStringTie\texon\t29541\t29650\t.\t-\t.\ttranscript_id \"TCONS_00000305\"; gene_id \"XLOC_000224\"; exon_number \"2\";",
        "C0006904\tStringTie\texon\t30400\t30498\t.\t-\t.\ttranscript_id \"TCONS_00000305\"; gene_id \"XLOC_000224\"; exon_number \"3\";",
        "C0006904\tStringTie\texon\t63368\t63426\t.\t-\t.\ttranscript_id \"TCONS_00000305\"; gene_id \"XLOC_000224\"; exon_number \"4\";"
    ]

# gtf_list = [
#         "chr10p\tambMex60DD\tgene\t1314711\t1340174\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; gene_name \"AMEX60DD000006\"",
#         "chr10p\tambMex60DD\ttranscript\t1314711\t1340174\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD201000006.1\"; gene_name \"LOC115464621_[nr]|ZNF268_[hs]\"; homolog \"XP_030050844.1\"; ORF_type \"Putative short PTC\"; CDS \"ATGAACACCCTCACAATGGAGTTACCCTTTGAATTTTCTGAAAGTGAAACAACTTTCGATGAAACTGATCATTTATGGCAACATCAGAGATCTCTCACCGAAGAGAAAGAAGATAAACATTTTGAATGCTACAAGCCCTCTACAGAAATAAATAATCTATTAATACATCAGAGAAATCTTCCCGGGGTGAAACCATATGCATGTTCTGAATGTGATAAGACTTTCAAGCAAAAGAGTGAACTATTGAGTCATCAGAGAATTCGCACTGTGGAGAAACCATATGCTTGTTCTGAATGTGATAAGACTTTCAAGCAAAAGAGTGAACTATTGAGTCATCAGAGAATTCACACTGGGGTGAAACCATACACATGTTCTGATTGTGATAAGTCTTTCACGGTGAAGTGTAATCTTTTGACACACCAGAGAAATCACACTGGGGTGAAACCATATACATGTTCTGAATGTCATAAGGCTTTCAAGCAAAAGAGTGAACTATTGATTCATCAGAGAATTCACACTGGGGTGAAACCATATACATGTTCTGAATGTGATAAGGCTTTCATGCGAAAGAGTGAACTATTGAGTCATCAGAGAATTCACACTGGGGAGAAACCATACACATGTTCTGATTGTGATAAGTCTTTCACGGTGAAGTGTAATCTTTTGACACACCAGAGAAATCACACTGGGGTGAAACCATATACATGTTCTGAATGTCATAAGGCTTTCAAGCAAAAGAGTGAACTATTGATTCATCAGAGAATTCACACTGGGGTGAAACCATATACATGTTCTGAATGTGATAAGGCTTTCATGCGAAAGAGTGAACTATTGAGTCATCAGAGAATTCACACTGGGGAGAAACCATATACATGTTCTGAATGTGATATGGCTTTCAAGCGAAGGGATCAACTTGTCATACATCAGAGTAATCATACTGGGGTGAAACCTTATGCATGTTCTGAATGTGATAAGGCTTTCAAGCAAAAGAATAAACTATTGATTCATCAGAGAATTCACACTGGGGAGAAACCATACACATGTTCTGAATGTGATAAGTCTTTCTCTGTGAAGTATAATCTTTTGACACACCAGAGAAGTCACACTGGGGTGAAACCTTATGCTTGCTCTGAATGTGATAAGGCTTTCGCGCAAAGGGGTAATCTATTGAGTCATCAGAGAATTCACACTGTGGAGAAACCCTATACATGCTCTGAATGTGATAAGGCCTTCAAGCGAAAGAGTGAACTATTGTGTCATCAGAGAATTCACACTGGGGTGAAACCATACACATGTTCTGAATGTGATATGTCTTTCACCGTGAAGTATAATCGTTTGACACACCAGAGAAGTCACACTGGGGTGAAACCATATGCATGCTCTGAATGTGATAAGGTTTTCAAGCATAGGGGTAATCTATTGAGTCATCAGAGAAATCACACTGGGGTGAAACCATATACATGTTCTGAATGTGATAAGGCTTTCAATCAAAAGAGTAAACTATTGATTCATCAGAGAATTCACACTGGGGTGAAACCATACACATGTTCTGAATGTGATGAGTCTTTCACAGTGAAGACTAATCTTTTGACACACCAGAGAAATCACACTGGGGAGAAATCATACACATGTTCCGAATGTGATAAGGCTTTCAAGCGAAATGATCAACTTGTGTTACATTTGAGAAATCACACTGAGTCTTTCAATCAAGAAGAGCAAACTATTGATACATCCGAGAAATCACACTGGTGAGAAACCCTAAATATGTTCTGAATGCAATGTCTTTCAAGCAATAAGGTGAACTAGGGCTGCACCAGAGAAATCACACTTACATGTTCTCAGTGTGATAAAGCTTTCAAGCATAATGAGAAACCTGTGATACATCAGAGAAATTACACTGTGAGTTTGCAGAAAAGCCTGACCTATTCCTGCATCACAAAAGAAATTACATGGGGGTGGGGGGCGGGACGGCGGGAGCCATATACATGTACTAAATGAAGACTTTCAAGTACAGTGGATATTCATAAAAGGTGTTGACACGGACTACTCGGATGCCCAAAACATCCACAACTTACAAATTCTCTTGGGCCCTGCTGTTTTGTGATGTATGATTTATGTATTGAATTAAAGGAAAGTGTCTTGTTATTTGGATTCATGAATAATTGA\"; peptide \"MNTLTMELPFEFSESETTFDETDHLWQHQRSLTEEKEDKHFECYKPSTEINNLLIHQRNLPGVKPYACSECDKTFKQKSELLSHQRIRTVEKPYACSECDKTFKQKSELLSHQRIHTGVKPYTCSDCDKSFTVKCNLLTHQRNHTGVKPYTCSECHKAFKQKSELLIHQRIHTGVKPYTCSECDKAFMRKSELLSHQRIHTGEKPYTCSDCDKSFTVKCNLLTHQRNHTGVKPYTCSECHKAFKQKSELLIHQRIHTGVKPYTCSECDKAFMRKSELLSHQRIHTGEKPYTCSECDMAFKRRDQLVIHQSNHTGVKPYACSECDKAFKQKNKLLIHQRIHTGEKPYTCSECDKSFSVKYNLLTHQRSHTGVKPYACSECDKAFAQRGNLLSHQRIHTVEKPYTCSECDKAFKRKSELLCHQRIHTGVKPYTCSECDMSFTVKYNRLTHQRSHTGVKPYACSECDKVFKHRGNLLSHQRNHTGVKPYTCSECDKAFNQKSKLLIHQRIHTGVKPYTCSECDESFTVKTNLLTHQRNHTGEKSYTCSECDKAFKRNDQLVLHLRNHTESFNQEEQTIDTSEKSHW*ETLNMF*MQCLSSNKVN*GCTREITLTCSQCDKAFKHNEKPVIHQRNYTVSLQKSLTYSCITKEITWGWGAGRREPYTCTK*RLSSTVDIHKRC*HGLLGCPKHPQLTNSLGPCCFVMYDLCIELKESVLLFGFMNN*\";",
#         "chr10p\tambMex60DD\texon\t1314711\t1318115\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD201000006.1\"; exon_number \"1\";",
#         "chr10p\tambMex60DD\texon\t1339931\t1340174\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD201000006.1\"; exon_number \"2\";",
#         "chr10p\tambMex60DD\tCDS\t1315260\t1317425\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD201000006.1\";",
#         "chr10p\tambMex60DD\ttranscript\t1315235\t1340174\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.2\"; gene_name \"ZNF300_[nr]|N/A_[hs]\"; homolog \"XP_012905845.1\"; ORF_type \"Putative short PTC\"; CDS \"ATGAACACCCTCACAATGGAGTTACCCTTTGAATTTTCTGAAAGTGAAACAACTTTCGATGAAACTGATCATTTATGGCAACATCAGAGATCTCTCACCGAAGAGAAAGAAGATAAACATTTTGAATGCTACAAGCCCTCTACAGAAATAAATAATCTATTAATACATCAGAGAAATCTTCCCGGGGTGAAACCATATGCATGTTCTGAATGTGATAAGACTTTCAAGCAAAAGAGTGAACTATTGAGTCATCAGAGAATTCGCACTGTGGAGAAACCATATGCTTGTTCTGAATGTGATAAGACTTTCAAGCAAAAGAGTGAACTATTGAGTCATCAGAGAATTCACACTGGGGTGAAACCATACACATGTTCTGATTGTGATAAGTCTTTCACGGTGAAGTGTAATCTTTTGACACACCAGAGAAATCACACTGGGGTGAAACCATATACATGTTCTGAATGTCATAAGGCTTTCAAGCAAAAGAGTGAACTATTGATTCATCAGAGAATTCACACTGGGGTGAAACCATATACATGTTCTGAATGTGATAAGGCTTTCATGCGAAAGAGTGAACTATTGAGTCATCAGAGAATTCACACTGGGGAGAAACCATACACATGTTCTGATTGTGATAAGTCTTTCACGGTGAAGTGTAATCTTTTGACACACCAGAGAAATCACACTGGGGTGAAACCATATACATGTTCTGAATGTCATAAGGCTTTCAAGCAAAAGAGTGAACTATTGATTCATCAGAGAATTCACACTGGGGTGAAACCATATACATGTTCTGAATGTGATAAGGCTTTCATGCGAAAGAGTGAACTATTGAGTCATCAGAGAATTCACACTGGGGAGAAACCATATACATGTTCTGAATGTGATATGGCTTTCAAGCGAAGGGATCAACTTGTCATACATCAGAGTAATCATACTGGGGTGAAACCTTATGCATGTTCTGAATGTGATAAGGCTTTCAAGCAAAAGAATAAACTATTGATTCATCAGAGAATTCACACTGGGGAGAAACCATACACATGTTCTGAATGTGATAAGTCTTTCTCTGTGAAGTATAATCTTTTGACACACCAGAGAAGTCACACTGGGGTGAAACCTTATGCTTGCTCTGAATGTGATAAGGCTTTCGCGCAAAGGGGTAATCTATTGAGTCATCAGAGAATTCACACTGTGGAGAAACCCTATACATGCTCTGAATGTGATAAGGCCTTCAAGCGAAAGAGTGAACTATTGTGTCATCAGAGAATTCACACTGGGGTGAAACCATACACATGTTCTGAATGTGATATGTCTTTCACCGTGAAGTATAATCGTTTGACACACCAGAGAAGTCACACTGGGGTGAAACCATATGCATGCTCTGAATGTGATAAGGTTTTCAAGCATAGGGGTAATCTATTGAGTCATCAGAGAATTCACACTGGGGTGAAACCATACACATGTTCTGAATGTGATGAGTCTTTCACAGTGAAGACTAATCTTTTGACACACCAGAGAAATCACACTGGGGAGAAATCATACACATGTTCCGAATGTGATAAGGCTTTCAAGCGAAATGATCAACTTGTGTTACATTTGAGAAATCACACTGAGTCTTTCAATCAAGAAGAGCAAACTATTGATACATCCGAGAAATCACACTGGTGAGAAACCCTAAATATGTTCTGAATGCAATGTCTTTCAAGCAATAAGGTGAACTAGGGCTGCACCAGAGAAATCACACTTACATGTTCTCAGTGTGATAAAGCTTTCAAGCATAATGAGAAACCTGTGATACATCAGAGAAATTACACTGTGAGTTTGCAGAAAAGCCTGACCTATTCCTGCATCACAAAAGAAATTACATGGGGGTGGGGGGCGGGACGGCGGGAGCCATATACATGTACTAAATGA\"; peptide \"MNTLTMELPFEFSESETTFDETDHLWQHQRSLTEEKEDKHFECYKPSTEINNLLIHQRNLPGVKPYACSECDKTFKQKSELLSHQRIRTVEKPYACSECDKTFKQKSELLSHQRIHTGVKPYTCSDCDKSFTVKCNLLTHQRNHTGVKPYTCSECHKAFKQKSELLIHQRIHTGVKPYTCSECDKAFMRKSELLSHQRIHTGEKPYTCSDCDKSFTVKCNLLTHQRNHTGVKPYTCSECHKAFKQKSELLIHQRIHTGVKPYTCSECDKAFMRKSELLSHQRIHTGEKPYTCSECDMAFKRRDQLVIHQSNHTGVKPYACSECDKAFKQKNKLLIHQRIHTGEKPYTCSECDKSFSVKYNLLTHQRSHTGVKPYACSECDKAFAQRGNLLSHQRIHTVEKPYTCSECDKAFKRKSELLCHQRIHTGVKPYTCSECDMSFTVKYNRLTHQRSHTGVKPYACSECDKVFKHRGNLLSHQRIHTGVKPYTCSECDESFTVKTNLLTHQRNHTGEKSYTCSECDKAFKRNDQLVLHLRNHTESFNQEEQTIDTSEKSHW*ETLNMF*MQCLSSNKVN*GCTREITLTCSQCDKAFKHNEKPVIHQRNYTVSLQKSLTYSCITKEITWGWGAGRREPYTCTK*\";",
#         "chr10p\tambMex60DD\texon\t1315235\t1315910\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.2\"; exon_number \"1\";",
#         "chr10p\tambMex60DD\texon\t1315995\t1318115\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.2\"; exon_number \"2\";",
#         "chr10p\tambMex60DD\texon\t1339931\t1340174\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.2\"; exon_number \"3\";",
#         "chr10p\tambMex60DD\tCDS\t1315428\t1315910\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.2\";",
#         "chr10p\tambMex60DD\tCDS\t1315995\t1317425\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.2\";",
#         "chr10p\tambMex60DD\ttranscript\t1315505\t1318115\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.3\"; gene_name \"LOC115464621_[nr]|ZNF268_[hs]\"; homolog \"XP_030050844.1\"; ORF_type \"N-terminal PTC\"; CDS \"ATGAACACCCTCACAATGGAGTTACCCTTTGAATTTTCTGAAAGTGAAACAACTTTCGATGAAACTGATCATTTATGGCAACATCAGAGATCTCTCACCGAAGAGAAAGAAGATAAACATTTTGAATGCTACAAGCCCTCTACAGAAATAAATAATCTATTAATACATCAGAGAAATCTTCCCGGGGTGAAACCATATGCATGTTCTGAATGTGATAAGACTTTCAAGCAAAAGAGTGAACTATTGAGTCATCAGAGAATTCGCACTGTGGAGAAACCATATGCTTGTTCTGAATGTGATAAGACTTTCAAGCAAAAGAGTGAACTATTGAGTCATCAGAGAATTCACACTGGGGTGAAACCATACACATGTTCTGATTGTGATAAGTCTTTCACGGTGAAGTGTAATCTTTTGACACACCAGAGAAATCACACTGGGGTGAAACCATATACATGTTCTGAATGTCATAAGTCTTTCACGGTGAAGTGTAATCTTTTGACACACCAGAGAAATCACACTGGGGTGAAACCATATACATGTTCTGAATGTCATAAGGCTTTCAAGCAAAAGAGTGAACTATTGATTCATCAGAGAATTCACACTGGGGTGAAACCATATACATGTTCTGAATGTGATAAGGCTTTCATGCGAAAGAGTGAACTATTGAGTCATCAGAGAATTCACACTGGGGAGAAACCATATACATGTTCTGAATGTGATATGGCTTTCAAGCGAAGGGATCAACTTGTCATACATCAGAGTAATCATACTGGGGTGAAACCTTATGCATGTTCTGAATGTGATAAGGCTTTCAAGCAAAAGAATAAACTATTGATTCATCAGAGAATTCACACTGGGGAGAAACCATACACATGTTCTGAATGTGATAAGTCTTTCTCTGTGAAGTATAATCTTTTGACACACCAGAGAAGTCACACTGGGGTGAAACCTTATGCTTGCTCTGAATGTGATAAGGCTTTCGCGCAAAGGGGTAATCTATTGAGTCATCAGAGAATTCACACTGTGGAGAAACCCTATACATGCTCTGAATGTGATAAGGCCTTCAAGCGAAAGAGTGAACTATTGTGTCATCAGAGAATTCACACTGGGGTGAAACCATACACATGTTCTGAATGTGATATGTCTTTCACCGTGAAGTATAATCGTTTGACACACCAGAGAAGTCACACTGGGGTGAAACCATATGCATGCTCTGAATGTGATAAGGTTTTCAAGCATAGGGGTAATCTATTGAGTCATCAGAGAAATCACACTGGGGTGAAACCATATACATGTTCTGAATGTGATAAGGCTTTCAATCAAAAGAGTAAACTATTGATTCATCAGAGAATTCACACTGGGGTGAAACCATACACATGTTCTGAATGTGATGAGTCTTTCACAGTGAAGACTAATCTTTTGACACACCAGAGAAATCACACTGGGGAGAAATCATACACATGTTCCGAATGTGATAAGGCTTTCAAGCGAAATGATCAACTTGTGTTACATTTGAGAAATCACACTGAGTCTTTCAATCAAGAAGAGCAAACTATTGATACATCCGAGAAATCACACTGGTGAGAAACCCTAAATATGTTCTGAATGCAATGTCTTTCAAGCAATAAGGTGAACTAGGGCTGCACCAGAGAAATCACACTTACATGTTCTCAGTGTGATAAAGCTTTCAAGCATAATGAGAAACCTGTGATACATCAGAGAAATTACACT\"; peptide \"MNTLTMELPFEFSESETTFDETDHLWQHQRSLTEEKEDKHFECYKPSTEINNLLIHQRNLPGVKPYACSECDKTFKQKSELLSHQRIRTVEKPYACSECDKTFKQKSELLSHQRIHTGVKPYTCSDCDKSFTVKCNLLTHQRNHTGVKPYTCSECHKSFTVKCNLLTHQRNHTGVKPYTCSECHKAFKQKSELLIHQRIHTGVKPYTCSECDKAFMRKSELLSHQRIHTGEKPYTCSECDMAFKRRDQLVIHQSNHTGVKPYACSECDKAFKQKNKLLIHQRIHTGEKPYTCSECDKSFSVKYNLLTHQRSHTGVKPYACSECDKAFAQRGNLLSHQRIHTVEKPYTCSECDKAFKRKSELLCHQRIHTGVKPYTCSECDMSFTVKYNRLTHQRSHTGVKPYACSECDKVFKHRGNLLSHQRNHTGVKPYTCSECDKAFNQKSKLLIHQRIHTGVKPYTCSECDESFTVKTNLLTHQRNHTGEKSYTCSECDKAFKRNDQLVLHLRNHTESFNQEEQTIDTSEKSHW*ETLNMF*MQCLSSNKVN*GCTREITLTCSQCDKAFKHNEKPVIHQRNYT\";",
#         "chr10p\tambMex60DD\texon\t1315505\t1316786\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.3\"; exon_number \"1\";",
#         "chr10p\tambMex60DD\texon\t1316955\t1318115\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.3\"; exon_number \"2\";",
#         "chr10p\tambMex60DD\tCDS\t1315527\t1316786\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.3\";",
#         "chr10p\tambMex60DD\tCDS\t1316955\t1317425\t1000\t-\t.\tgene_id \"AMEX60DD000006\"; transcript_id \"AMEX60DD301000006.3\";"
#     ]

processed_data =separate_transcripts_with_same_cmp_ref_geneID(gtf_list)

for key, value in processed_data.items():
    print(f"Key: {key}")
   
    for line in value:
        print(f"    {line[:50]}...")  
    print("\n")  

